grief-dashboard/reddash/app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    "base_blueprint", __name__, template_folder="templates", static_folder="static",
)

grief-dashboard/reddash/app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for, session, g, make_response
from datetime import datetime, timedelta
from flask_babel import _, refresh

from reddash.app.base import blueprint
from reddash.app import app

import requests
import websocket
import json
import logging
import jwt

dashlog = logging.getLogger("reddash")


@blueprint.route("/error-<error>")
def route_errors(error):
    return render_template("errors/{}.html".format(error))


## Login & Registration


@blueprint.route("/callback", methods=["GET"])
def callback():
    try:
        code = request.args["code"]
    except KeyError:
        return render_template("login/login.html", status="1")
    requestobj = {
        "jsonrpc": "2.0",
        "id": 0,
        "method": "DASHBOARDRPC__GET_SECRET",
        "params": [],
    }
    if app.ws and app.ws.connected:
        with app.lock:
            try:
                app.ws.send(json.dumps(requestobj))
                result = json.loads(app.ws.recv())
            except (
                ConnectionRefusedError,
                websocket._exceptions.WebSocketConnectionClosedException,
                ConnectionResetError,
            ):
                return render_template("login/login.html", status="4")
            if "error" in result:
                if result["error"]["message"] == "Method not found":
                    return render_template("login/login.html", status="4")
                else:
                    dashlog.error(result["error"])
                    return render_template("login/login.html", status="5")
            if isinstance(result["result"], dict) and result["result"].get("disconnected", False):
                return render_template("login/login.html", status="4")
            secret = result["result"]["secret"]
    else:
        return render_template("login/login.html", status="4")
    redirectstr = app.variables["redirect"]
    data = {
        "client_id": int(app.variables["clientid"]),
        "client_secret": secret,
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": redirectstr,
        "scope": "identify",
    }
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    response = requests.post(
        "https://discordapp.com/api/v6/oauth2/token", data=data, headers=headers
    )
    try:
        token = response.json()["access_token"]
    except KeyError:
        dashlog.error(f"Failed to log someone in.\n{response.json()}")
        return render_template("login/login.html", status="2")
    new = requests.get(
        "https://discordapp.com/api/v6/users/@me", headers={"Authorization": f"Bearer {token}"},
    )
    new_data = new.json()
    if "id" in new_data:
        payload = {
            "userid": new_data["id"],
            "iat": datetime.utcnow(),
            "exp": datetime.utcnow() + timedelta(minutes=30),
        }
        token = jwt.encode(payload, app.jwt_secret_key, algorithm="HS256")
        session["id"] = token
        session[
            "avatar"
        ] = f"https://cdn.discordapp.com/avatars/{new_data['id']}/{new_data['avatar']}.png"
        session["username"] = new_data["username"]

        redirecting_to = "base_blueprint.index"
        arguments = {}
        if session.get("login_redirect"):
            redirecting_to = session["login_redirect"]["route"]
            arguments = session["login_redirect"]["kwargs"]
            del session["login_redirect"]

        return redirect(url_for(redirecting_to, **arguments))
    dashlog.error(f"Failed to obtain a user's profile.\n{new.json()}")
    return render_template("login/login.html", status="3")


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    if not session.get("id"):
        return render_template("login/login.html", status="0")
    return redirect(url_for("base_blueprint.index"))


@blueprint.route("/logout")
def logout():
    del session["id"]
    return redirect(url_for("base_blueprint.login"))


@blueprint.route("/blacklisted")
def blacklisted():
    return render_template("errors/blacklisted.html")


@blueprint.route("/setcolor", methods=["POST"])
def set_color():
    resp = make_response(jsonify({"status": 1}))
    resp.set_cookie("color", request.json.get("color"))
    return resp


@blueprint.route("/index")
@blueprint.route("/")
def index():
    return render_template("index.html")


@blueprint.route("/commands")
def commands():
    data = app.commanddata
    prefix = app.variables.get("prefix", ["[p]"])

    return render_template(
        "pages/commands.html", cogs=[k["name"] for k in data], data=data, prefixes=prefix
    )


@blueprint.route("/credits")
def credits():
    return render_template("pages/credits.html")


## Errors


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template("errors/403.html"), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template("errors/404.html"), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template("errors/500.html"), 500

grief-dashboard/reddash/app/base/templates/base-site.html
<!--
=========================================================
* * Black Dashboard - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)


* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!--
  This dashboard was based upon the Black Dashboard Theme, who's credits are above.
  It was changed and recoded by Neuro Assassin <@473541068378341376> to work with Red Discord Bot.
  The changes are protected under an MIT License, which can be found here: https://github.com/Cog-Creators/Red-Dashboard/blob/master/LICENSE
  Thank you to Red Discord Bot and all of its developers for making such an amazing bot that has allowed me to create this.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ botavatar }}">
  <link rel="icon" type="image/png" href="{{ botavatar }}">
  <title>
    {{ meta['title'] }} -{% block title %}{% endblock %}
  </title>
  <!-- Meta tags -->
  <meta content="{{ meta['title'] }} -{{ self.title() }}" property="og:title">
  <meta content="{{ meta['description'] }}" property="og:description">
  <meta content="Melon Dashboard" property="og:site_name">
  <meta content="{{ meta['icon'] }}" property="og:image">
  <meta content="{{ meta['color'] }}" name="theme-color">
  <!-- Fonts and icons -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="/static/assets/css/bootstrap-select.min.css?v=1.0.0">
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="/static/assets/css/black-dashboard.min.css?v=1.0.0" rel="stylesheet" />

  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body data="{{ color }}">
  {% include 'site_template/scripts.html' %}
  <div class="wrapper">

    {% include 'site_template/sidebar.html' %}

    <div class="main-panel">

      {% include 'site_template/navigation.html' %}

      <div class="content">

        {% block content %}{% endblock content %}

      </div>

      {% include 'site_template/footer.html' %}

    </div>

  </div>

  {% include 'site_template/fixed-plugin.html' %}

  {% include 'site_template/scripts-sidebar.html' %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}
  <script>
    $(document).ready(function () {
      // Sidebar active
      var path = window.location.pathname.split("/")[1]
      if (path === "") {
        path = "index"
      } else if (path === "guild") {
        path = "dashboard"
      }
      try {
        $("#nav" + path).addClass("active")
      } catch {
        $("#navdashboard").addClass("active")
      }
    })

    // Add data attributes to button's and a's
    c = localStorage.getItem("theme")
    if (localStorage.getItem("color") === "white") {
      $('body').addClass("white-content")
      $('nav').addClass("white-content")
      $('.prefixdiv').addClass("white-content")
    }
    // Add white border to seleted color
    $("span[data-color={{ color }}").addClass("active")
  </script>
  <script src="/static/assets/js/bootstrap-select.min.js"></script>
</body>

</html>

grief-dashboard/reddash/app/base/templates/login/login.html
{% extends "base-site.html" %}

{% block title %} {{ _('Login') }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    <div class="card">
      {% if status == '0' %}
      <div class="card-header">
        <h1 class="title">{{ _('Login') }}</h1>
      </div>
      {% if redirect %}
      <div class="card-body">
        <div class="row">
          <div class="col-1 px-md-1"></div>
          <div class="col-md-11 px-md-1">
            <h5>
              {{ _('Welcome to the grief dashboard, a lot of the magic here is hidden behind authorization. Want to see some of it? Login with Discord below.') }}
            </h5>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <a
          href="https://discord.com/api/oauth2/authorize?client_id={{ clientid }}&redirect_uri={{ redirect }}&response_type=code&scope=identify"><button
            class="btn">{{ _('Login with Discord') }}</button></a><br>
        {{ _('By clicking the button above, you acknowledge that you have read and agree to our Privacy Policy found <a href="{link}" target="_blank">here</a>.').format(link="https://privacy.grief.cloud) }}
      </div>
      {% else %}
      <div class="card-body">
        <div class="row">
          <div class="col-md-1 px-md-1"></div>
          <div class="col-md-11 px-md-1">
            <h5>
              {{ _('Welcome to the grief dashboard, a lot of the magic here is hidden behind authorization, but unfortunately, login is currently not available because grief is not connected to the dashboard.') }}
            </h5>
          </div>
        </div>
      </div>
      {% endif %}
      {% elif status == '1' %}
      <div class="card-header">
        <h1 class="title">{{ _('Login Failed') }}</h1>
      </div>
      {% if redirect %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>{{ _('Looks like you denied authorization. Made a mistake? Click the button below to try again.') }}</h5>
        </div>
      </div>
      <div class="card-footer">
        <a
          href="https://discord.com/api/oauth2/authorize?client_id={{ clientid }}&redirect_uri={{ redirect }}&response_type=code&scope=identify"><button
            class="btn">{{ _('Login with Discord') }}</button></a><br>
        {{ _('By clicking the button above, you acknowledge that you have read and agree to our Privacy Policy found <a href="{link}" target="_blank">here</a>.').format(link="https://privacy.grief.cloud") }}
      </div>
      {% else %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _("Looks like you denied authorization. Unfortunately, the dashboard's connection to the bot has terminated. Check back later.") }}
          </h5>
        </div>
      </div>
      {% endif %}
      {% elif status == '2' %}
      <div class="card-header">
        <h1 class="title">{{ _('Login Failed') }}</h1>
      </div>
      {% if redirect %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _('Looks like the bot owner may have not configured the dashboard properly. You can try again below if you believe this was a fluke. If this happens multiple times, please let the bot owner or server owner know.') }}
          </h5>
        </div>
      </div>
      <div class="card-footer">
        <a
          href="https://discord.com/api/oauth2/authorize?client_id={{ clientid }}&redirect_uri={{ redirect }}&response_type=code&scope=identify"><button
            class="btn">{{ _('Login with Discord') }}</button></a><br>
        {{ _('By clicking the button above, you acknowledge that you have read and agree to our Privacy Policy found <a href="{link}" target="_blank">here</a>.').format(link="https://privacy.grief.cloud") }}
      </div>
      {% else %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _("Looks like the bot owner may have not configured the dashboard properly. Unfortunately, the dashboard's connection to the bot has terminated. Check back later.") }}
          </h5>
        </div>
      </div>
      {% endif %}
      {% elif status == '3' %}
      <div class="card-header">
        <h1 class="title">{{ _('Login Failed') }}</h1>
      </div>
      {% if redirect %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _("Looks like something went wrong on Discord's end. Try to login again below, or check to see if Discord is having API issues.") }}
          </h5>
        </div>
      </div>
      <div class="card-footer">
        <a
          href="https://discord.com/api/oauth2/authorize?client_id={{ clientid }}&redirect_uri={{ redirect }}&response_type=code&scope=identify"><button
            class="btn">{{ _('Login with Discord') }}</button></a><br>
        {{ _('By clicking the button above, you acknowledge that you have read and agree to our Privacy Policy found <a href="{link}" target="_blank">here</a>.').format(link="https://privacy.grief.cloud") }}
      </div>
      {% else %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _("Looks like something went wrong on Discord's end. Unfortunately, the dashboard's connection to the bot has terminated. Check back later.") }}
          </h5>
        </div>
      </div>
      {% endif %}
      {% elif status == '4' %}
      <div class="card-header">
        <h1 class="title">{{ _('Login Failed') }}</h1>
      </div>
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>{{ _('Looks like the bot owner just terminated the connection to the bot. Check back later.') }}</h5>
        </div>
      </div>
      {% elif status == '5' %}
      <div class="card-header">
        <h1 class="title">{{ _('Login Failed') }}</h1>
      </div>
      {% if redirect %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _('Looks like something went wrong. Try to login again below. If this keeps happening, please report to bot owner or server owner.') }}
          </h5>
        </div>
      </div>
      <div class="card-footer">
        <a
          href="https://discord.com/api/oauth2/authorize?client_id={{ clientid }}&redirect_uri={{ redirect }}&response_type=code&scope=identify"><button
            class="btn">{{ _('Login with Discord') }}</button></a><br>
        {{ _('By clicking the button above, you acknowledge that you have read and agree to our Privacy Policy found <a href="{link}" target="_blank">here</a>.').format(link="https://privacy.grief.cloud") }}
      </div>
      {% else %}
      <div class="card-body">
        <div class="col-md-1 px-md-1"></div>
        <div class="col-md-11 px-md-1">
          <h5>
            {{ _("Looks like something went wrong. Unfortunately, the dashboard's connection to the bot has terminated. Try again later. If it continues to occur, please report to bot owner or server owner.") }}
          </h5>
        </div>
      </div>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

{% endblock javascripts %}

grief-dashboard/reddash/app/base/templates/site_template/footer.html
<footer class="footer">
  <div class="container-fluid">
  </div>
</footer>

grief-dashboard/reddash/app/base/templates/site_template/navigation.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <div class="navbar-toggle d-inline">
        <button type="button" class="navbar-toggler">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <br />
      <a class="navbar-brand" href="javascript:void(0)">{{ _('{name} Dashboard').format(name=botname)}}</a>
    </div>
    {% if session.get("id") %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>

    <div class="collapse navbar-collapse" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="dropdown nav-item">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
            <div class="photo">
              <img src="{{ session.get('avatar') }}" alt="Profile Photo">
            </div>
            <b class="caret d-none d-lg-block d-xl-block"></b>
            <p class="d-lg-none">
              {{ _('Log out') }}
            </p>
          </a>
          <ul class="dropdown-menu dropdown-navbar">
            <li class="nav-link"><span class="nav-item dropdown-item">{{ session.get("username") }}</span></li>
            <li class="dropdown-divider"></li>
            <li class="nav-link"><a href="{{ url_for('base_blueprint.logout') }}"
                class="nav-item dropdown-item">{{ _('Log out') }}</a></li>
          </ul>
        </li>
        <li class="separator d-lg-none"></li>
      </ul>
    </div>
    {% endif %}
  </div>
</nav>
<div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="tim-icons icon-simple-remove"></i>
        </button>
      </div>
    </div>
  </div>
</div>
<!-- End Navbar -->

grief-dashboard/reddash/app/base/templates/site_template/scripts-sidebar.html
<script>
  $(document).ready(function () {
    $().ready(function () {
      $sidebar = $('.sidebar');
      $navbar = $('.navbar');
      $main_panel = $('.main-panel');
      $buttons = $('button');
      $as = $('a')
      $inputs = $('input')
      $textareas = $('textarea')
      $bcitems = $('.breadcrumb-item')

      $full_page = $('.full-page');

      $sidebar_responsive = $('body > .navbar-collapse');
      sidebar_mini_active = true;
      white_color = false;

      white_color = localStorage.getItem("color") === "white"


      window_width = $(window).width();

      fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

      reversed_locales = { 'Afrikaans - Suid-Afrika': 'af_ZA', 'العربية - المملكة العربية السعودية': 'ar_SA', 'български - България': 'bg_BG', 'català - Espanya': 'ca_ES', 'čeština - Česko': 'cs_CZ', 'dansk - Danmark': 'da_DK', 'Deutsch - Deutschland': 'de_DE', 'Ελληνικά - Ελλάδα': 'el_GR', 'English': 'en', 'español - España': 'es_ES', 'suomi - Suomi': 'fi_FI', 'français': 'fr', 'français - France': 'fr_FR', 'עברית - ישראל': 'he_IL', 'magyar - Magyarország': 'hu_HU', 'Indonesia - Indonesia': 'id_ID', 'italiano - Italia': 'it_IT', '日本語 - 日本': 'ja_JP', '한국어 - 대한민국': 'ko_KR', 'Nederlands - Nederland': 'nl_NL', 'norsk bokmål - Norge': 'no_NO', 'polski - Polska': 'pl_PL', 'português - Brasil': 'pt_BR', 'português - Portugal': 'pt_PT', 'română - România': 'ro_RO', 'русский - Россия': 'ru_RU', 'slovenčina - Slovensko': 'sk_SK', 'svenska - Sverige': 'sv_SE', 'Türkçe - Türkiye': 'tr_TR', 'українська - Україна': 'uk_UA', 'Tiếng Việt - Việt Nam': 'vi_VN', '中文 - 中国': 'zh_CN', '中文 - 中國香港特別行政區': 'zh_HK', '中文 - 台灣': 'zh_TW' }


      $("#changelocale").click(function (event) {
        var locale = $("#localepicker").val()
        var real_locale = reversed_locales[locale]
        var redirect = "{{ url_for('base_blueprint.index') }}".replace("{{ session.get('lang_code') }}", real_locale)
        window.location.replace(redirect)
      })
      $('.fixed-plugin a').click(function (event) {
        if ($(this).hasClass('switch-trigger')) {
          if (event.stopPropagation) {
            event.stopPropagation();
          } else if (window.event) {
            window.event.cancelBubble = true;
          }
        }
      });

      $('.fixed-plugin .background-color span').click(function () {
        $(this).siblings().removeClass('active');
        $(this).addClass('active');

        var new_color = $(this).data('color');

        if ($sidebar.length != 0) {
          $sidebar.attr('data', new_color);
        }

        if ($main_panel.length != 0) {
          $main_panel.attr('data', new_color);
        }

        if ($full_page.length != 0) {
          $full_page.attr('filter-color', new_color);
        }

        if ($sidebar_responsive.length != 0) {
          $sidebar_responsive.attr('data', new_color);
        }

        $("body").attr("data", new_color)

        var xhr = new XMLHttpRequest();
        var url = "{{ url_for('base_blueprint.set_color') }}"
        xhr.open("POST", url, true)
        xhr.setRequestHeader("Content-Type", "application/json")

        data = {
          "color": new_color
        }

        try {
          xhr.send(JSON.stringify(data))
        } catch (error) {
          console.log(error)
        }

      });

      $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function () {
        var $btn = $(this);

        if (sidebar_mini_active == true) {
          $('body').removeClass('sidebar-mini');
          sidebar_mini_active = false;
          blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
        } else {
          $('body').addClass('sidebar-mini');
          sidebar_mini_active = true;
          blackDashboard.showSidebarMessage('Sidebar mini activated...');
        }

        // we simulate the window Resize so the charts will get updated in realtime.
        var simulateWindowResize = setInterval(function () {
          window.dispatchEvent(new Event('resize'));
        }, 180);

        // we stop the simulation of Window Resize after the animations are completed
        setTimeout(function () {
          clearInterval(simulateWindowResize);
        }, 1000);
      });

      $('.switch-change-color input').on("switchChange.bootstrapSwitch", function () {
        var $btn = $(this);
        if (white_color == true) {

          $('body').addClass('change-background');
          setTimeout(function () {
            $('body').removeClass('change-background');
            $('body').removeClass('white-content');
            $('.dropdown-menu').removeClass('white-content')
            $('.list-group').removeClass('white-text')
            $('ol.breadcrumb').removeClass('white-content')
            $('.navbar').removeClass('white-content')
          }, 900);
          white_color = false;
        } else {

          $('body').addClass('change-background');
          setTimeout(function () {
            $('body').removeClass('change-background');
            $('body').addClass('white-content');
            $('.dropdown-menu').addClass('white-content')
            $('.list-group').addClass('white-text')
            $('ol.breadcrumb').addClass('white-content')
            $('.navbar').addClass('white-content')
          }, 900);

          white_color = true;
        }
      });

      $('.light-badge').click(function () {
        $('body').addClass('white-content');
        $('.dropdown-menu').addClass('white-content')
        $('.list-group').addClass('white-text')
        $('ol.breadcrumb').addClass('white-content')
        $('.navbar').addClass('white-content')

        localStorage.setItem("color", "white")
      });

      $('.dark-badge').click(function () {
        $('body').removeClass('white-content');
        $('.dropdown-menu').removeClass('white-content')
        $('.list-group').removeClass('white-text')
        $('ol.breadcrumb').removeClass('white-content')
        $('.navbar').removeClass('white-content')

        localStorage.setItem("color", "black")
      });
    });
  });
</script>

grief-dashboard/reddash/app/base/templates/site_template/scripts.html
<!--   Core JS Files   -->
<script src="/static/assets/js/core/jquery.min.js"></script>
<script src="/static/assets/js/core/popper.min.js"></script>
<script src="/static/assets/js/core/bootstrap.min.js"></script>
<script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<!--  Notifications Plugin    -->
<script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
<script src="/static/assets/js/black-dashboard.min.js?v=1.0.0"></script>

grief-dashboard/reddash/app/base/templates/site_template/sidebar.html
<div class="sidebar">
  <div class="sidebar-wrapper">
    <div class="logo">
      <a class="simple-text logo-mini clickable dontcolor" target="_blank">
        <i class="tim-icons icon-atom"></i>
      </a>
      <a class="simple-text logo-normal clickable dontcolor" target="_blank">
        {{ _('Dashboard') }}
      </a>
    </div>

    {% if session.get("id") %}
    <ul class="nav">
      <li id="navindex">
        <a href="{{ url_for('base_blueprint.index') }}">
          <i class="tim-icons icon-chart-pie-36"></i>
          <p>{{ _('Home') }}</p>
        </a>
      </li>
      <li id="navcommands">
        <a href="{{ url_for('base_blueprint.commands') }}">
          <i class="tim-icons icon-molecule-40"></i>
          <p>{{ _('Commands') }}</p>
        </a>
      </li>
      <li id="navdashboard">
        <a href="{{ url_for('dashboard_blueprint.dashboard') }}">
          <i class="tim-icons icon-controller"></i>
          <p>{{ _('Dashboard') }}</p>
        </a>
      </li>
      <li id="navcredits">
        <a href="{{ url_for('base_blueprint.credits') }}">
          <i class="tim-icons icon-book-bookmark"></i>
          <p>{{ _('Credits') }}</p>
        </a>
      </li>
      <li>
        <a href="{{ url_for('base_blueprint.logout') }}"">
          <i class=" tim-icons icon-user-run"></i>
          <p>{{ _('Logout') }}</p>
        </a>
      </li>
    </ul>
    {% else %}
    <ul class="nav">
      <li id="navindex">
        <a href="{{ url_for('base_blueprint.index') }}">
          <i class="tim-icons icon-chart-pie-36"></i>
          <p>{{ _('Home') }}</p>
        </a>
      </li>
      {% if redirect %}
      <li id="navcommands">
        <a href="{{ url_for('base_blueprint.commands') }}">
          <i class="tim-icons icon-molecule-40"></i>
          <p>{{ _('Commands') }}</p>
        </a>
      </li>
      {% endif %}
      <li id="navcredits">
        <a href="{{ url_for('base_blueprint.credits') }}">
          <i class="tim-icons icon-book-bookmark"></i>
          <p>{{ _('Credits') }}</p>
        </a>
      </li>
      <li id="navlogin">
        <a href="{{ url_for('base_blueprint.login') }}">
          <i class="tim-icons icon-key-25"></i>
          <p>{{ _('Login') }}</p>
        </a>
      </li>
    </ul>
    {% endif %}
  </div>
</div>