grief-dashboard/reddash/app/dashboard/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    "dashboard_blueprint", __name__, template_folder="templates", static_folder="static",
)

grief-dashboard/reddash/app/dashboard/routes.py
from reddash.app import app
from reddash.app.dashboard import blueprint
from flask import render_template, redirect, url_for, session, request, jsonify, Response, g
from flask_babel import _, refresh
from jinja2 import TemplateNotFound
import traceback
import websocket
import json
import time
import random
import logging
import datetime

dashlog = logging.getLogger("reddash")


@blueprint.route("/dashboard")
def dashboard():
    if not session.get("id"):
        return redirect(url_for("base_blueprint.login"))
    return render_template("dashboard.html")


@blueprint.route("/guild/<guild>")
def guild(guild):
    if not session.get("id"):
        return redirect(url_for("base_blueprint.login"))

    try:
        int(guild)
    except ValueError:
        raise ValueError("Guild ID must be integer")

    # We won't disconnect the websocket here, even if it fails, so that the main updating thread doesnt run into issues
    try:
        request = {
            "jsonrpc": "2.0",
            "id": random.randint(1, 1000),
            "method": "DASHBOARDRPC__GET_SERVER",
            "params": [int(g.id), int(guild)],
        }
        with app.lock:
            app.ws.send(json.dumps(request))
            result = json.loads(app.ws.recv())
            data = {}
            if "error" in result:
                if result["error"]["message"] == "Method not found":
                    data = {"status": 0, "message": "Not connected to bot"}
                else:
                    dashlog.error(result["error"])
                    data = {"status": 0, "message": "Something went wrong"}
            if isinstance(result["result"], dict) and result["result"].get("disconnected", False):
                data = {"status": 0, "message": "Not connected to bot"}
        if not data:
            data = {"status": 1, "data": result["result"]}
    except:
        data = {"status": 0, "message": "Not connected to bot"}
    return render_template("guild.html", data=data)

grief-dashboard/reddash/app/dashboard/templates/dashboard.html
{% extends "base-site.html" %}

{% block title %} {{ _('Dashboard') }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card card-profile">
            <div class="card-body">
                <h6 class="card-category text-gray">{{ _('Dashboard') }}</h6>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-11">
                            <h5>{{ (_("Welcome to the interactive dashboard, where you can control your bot via this easy-to-use interface. Choose a server that you have elevated permissions in below. If you don't see your server below, check to make sure that your server's owner has set roles with <code>{command}</code>").format(command="[p]dashboard roles create"))|safe }}
                            </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card card-profile">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <form class="form-inline d-flex justify-content-center md-form form-sm mt-0">
                            <i class="fas fa-search" aria-hidden="true"></i>
                            <input class="form-control form-control-sm ml-3 w-75" id="guildsearch" type="text"
                                placeholder="{{ _('Search') }}" aria-label="Search">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" id="serverrow">
    <div class="col-md-12">
        <h1>{{ _('Loading servers...') }}</h1>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.0.4"></script>
<script>
    // Since the serer loading could take who knows how long, we'll load in JS so it says "Loading..."" in the page
    $(document).ready(function () {
        var xhr = new XMLHttpRequest();
        var url = "{{ url_for('api_blueprint.getservers') }}"
        xhr.open("GET", url, true)
        xhr.setRequestHeader("Content-Type", "application/json")
        xhr.onreadystatechange = function () {
            if (xhr.readyState !== 4) { return }
            var json = JSON.parse(xhr.responseText)
            if (json.status === 0) {
                $("#serverrow").html(`<div class="col-md-12"><h1>${json["message"]}</h1></div>`)
            } else {
                if (json.data.length === 0) {
                    $("#serverrow").html(`<div class="col-md-12"><h1>{{ _("You're not in any servers with elevated permissions!") }}</h1></div>`)
                } else {
                    var base_guild_url = "{{ url_for('dashboard_blueprint.guild', guild='123456789123456789') }}"
                    $("#serverrow").html("")
                    for (let g of json.data) {
                        var current_guild_url = base_guild_url.replace("123456789123456789", g.id)
                        $("#serverrow").append(`
                            <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-12 guildcard" style="margin-bottom: 50px">
                                <a href="${current_guild_url}">
                                    <div class="card h-100" onmouseover="playGif(this)" onmouseout="stopGif(this)">
                                        <img class="card-img-top" src="${g.icon}png" alt="Card image cap" data-src-url="${g.icon}" data-is-animated=${g.animated}>
                                        <div class="card-body">
                                            <h5 class="card-title">${g.name}</h5>
                                            <p class="card-text">Owner: ${g.owner}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        `)
                    }
                }
            }
        }
        try {
            xhr.send()
        } catch (error) {
            console.log(error)
        }
    })

    function playGif(elm) {
        var img = $(elm).find("img")
        if (img.attr('data-is-animated') === "true") {
            img.attr("src", `${img.attr("data-src-url")}gif`)
        }
    }
    function stopGif(elm) {
        var img = $(elm).find("img")
        if (img.attr('data-is-animated') === "true") {
            img.attr("src", `${img.attr("data-src-url")}png`)
        }
    }
    $(document).ready(function () {
        $("#guildsearch").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $('.guildcard').filter(function () {
                var name = $(this).find('h5').text().toLowerCase()
                var list = [name]
                var options = {
                    threshold: '0.3'
                }
                var fuse = new Fuse(list, options)
                $(this).toggle(fuse.search(value).length === 1 || value === "")
            });
        });
    });
</script>
{% endblock javascripts %}

grief-dashboard/reddash/app/dashboard/templates/index.html
{% extends "base-site.html" %}

{% block title %} {{ _('Home') }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">

  <div class="col-12">
    <div class="card card-chart">
      <div class="card-body">
        <div class="row">
          <div class="col-lg-3">
            <br />
            <img src="{{ botavatar }}"
              style="height: 200px; width: 200px; border-radius: 50%; margin: auto; display: block;"
            >
            <br />
          </div>
          <div class="col-lg-8">
            <h4>{{ botname }}</h4>
            <br />
            <h4> 
grief is one of the most advanced bots on Discord. with over 500 commands and over 20 message-based events, grief is a bot that enhances the Discord experience like no other. whether it's integration with other services and platforms or its advanced moderation commands, servers that use Melanie are the best servers on Discord. </h4>
            <br />
            {% if redirect %}
            <a href="{{ invite }}" target="_blank">Invite</a>
            {% endif %}
            {% if support %}
            • <a href="{{ support }}" target="_blank">{{ _('Join support server') }}</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{% if redirect %}
<div class="row">
  <div class="col-lg-4">
    <div class="card card-chart">
      <div class="card-header">
        <h5 class="card-category">{{ _('Total Servers') }}</h5>
        <h3 class="card-title"><i class="tim-icons icon-bank text-primary"></i><span id="servers">{{ servers }}</span>
        </h3>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card card-chart">
      <div class="card-header">
        <h5 class="card-category">{{ _('Total Users') }}</h5>
        <h3 class="card-title"><i class="tim-icons icon-single-02 text-info"></i><span id="users">{{ users }}</span>
        </h3>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card card-chart">
      <div class="card-header">
        <h5 class="card-category">{{ _('Been up for') }}</h5>
        <h3 class="card-title"><i class="tim-icons icon-badge text-success"></i><span
            id="onlineusers">{{ uptime }}</span></h3>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>
</script>

{% endblock javascripts %}

grief-dashboard/reddash/app/dashboard/templates/page-403.html
{% extends "errors/403.html" %}

grief-dashboard/reddash/app/dashboard/templates/page-404.html
{% extends "errors/404.html" %}

grief-dashboard/reddash/app/dashboard/templates/page-500.html
{% extends "errors/500.html" %}

grief-dashboard/reddash/app/dashboard/templates/third_party/spotify.html
{% extends "base-site.html" %}

{% block title %} {{ _('Third Party Spotify') }} {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <div class="card card-profile">
            <div class="card-body">
                <h6 class="card-category text-gray">{{ _('Spotify OAuth Redirect') }}</h6>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-11">
                            {% if context == '1' %}
                            <h5>{{ _("Successfully connected your Spotify account.  You may now close this tab.") }}
                            </h5>
                            {% else %}
                            {% if context == '2' %}
                            <h5>{{ _("We had trouble contacting the bot to authenticate: {message}").format(message=msg) }}
                            </h5>
                            {% else %}
                            <h5>{{ _("We failed to authenticate you: {message}").format(message=msg) }}
                            </h5>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                {{ _('This is a Third Party integration.  By using this application, you acknowledge that you have read the Third Party disclaimer found <a href="{link}">here</a>').format(link="https://github.com/Cog-Creators/Red-Dashboard/blob/master/documents/Third%20Party%20Disclaimer.md") }}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}